from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

from .bulk import generate_list, validate_docs, validate_list
from .enrich import CEPEnrichment, CNPJEnrichment, enrich_cep, enrich_cnpj

try:
    __version__: str = _pkg_version("brdocuments")
except PackageNotFoundError:
    __version__ = "0.0.0.dev0"

from .generators import (
    generate_cep,
    generate_cnh,
    generate_cnj,
    generate_cnpj,
    generate_cns,
    generate_cpf,
    generate_ie,
    generate_pis,
    generate_renavam,
    generate_titulo_eleitor,
)
from .parsers import (
    CEPData,
    CNHData,
    CNJData,
    CNPJData,
    CNSData,
    CPFData,
    IEData,
    NFEData,
    PISData,
    RenavamData,
    TituloData,
    format_cep,
    format_cnh,
    format_cnj,
    format_cnpj,
    format_cns,
    format_cpf,
    format_ie,
    format_nfe,
    format_pis,
    format_renavam,
    format_titulo_eleitor,
    parse_cep,
    parse_cnh,
    parse_cnj,
    parse_cnpj,
    parse_cns,
    parse_cpf,
    parse_ie,
    parse_nfe,
    parse_pis,
    parse_renavam,
    parse_titulo_eleitor,
)
from .secure import BRDocFilter, redact_text
from .validators import (
    PixKeyType,
    classify_pix,
    is_valid_cep,
    is_valid_cnh,
    is_valid_cnj,
    is_valid_cnpj,
    is_valid_cns,
    is_valid_cpf,
    is_valid_ie,
    is_valid_nfe,
    is_valid_pis,
    is_valid_renavam,
    is_valid_titulo_eleitor,
)

__all__ = [
    "BRDocFilter",
    "CEPData",
    "CEPEnrichment",
    "CNHData",
    "CNJData",
    "CNPJData",
    "CNPJEnrichment",
    "CNSData",
    "CPFData",
    "IEData",
    "NFEData",
    "PISData",
    "PixKeyType",
    "RenavamData",
    "TituloData",
    "__version__",
    "classify_pix",
    "enrich_cep",
    "enrich_cnpj",
    "format_cep",
    "format_cnh",
    "format_cnj",
    "format_cnpj",
    "format_cns",
    "format_cpf",
    "format_ie",
    "format_nfe",
    "format_pis",
    "format_renavam",
    "format_titulo_eleitor",
    "generate_cep",
    "generate_cnh",
    "generate_cnj",
    "generate_cnpj",
    "generate_cns",
    "generate_cpf",
    "generate_ie",
    "generate_list",
    "generate_pis",
    "generate_renavam",
    "generate_titulo_eleitor",
    "is_valid_cep",
    "is_valid_cnh",
    "is_valid_cnj",
    "is_valid_cnpj",
    "is_valid_cns",
    "is_valid_cpf",
    "is_valid_ie",
    "is_valid_nfe",
    "is_valid_pis",
    "is_valid_renavam",
    "is_valid_titulo_eleitor",
    "parse_cep",
    "parse_cnh",
    "parse_cnj",
    "parse_cnpj",
    "parse_cns",
    "parse_cpf",
    "parse_ie",
    "parse_nfe",
    "parse_pis",
    "parse_renavam",
    "parse_titulo_eleitor",
    "redact_text",
    "validate_docs",
    "validate_list",
]
